title: My Awesome Home
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /local/card-example.js
    type: js

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
    # View tab title.
  - title: Wentylacja_1
    # Optional unique id for direct access /lovelace/${id}
    id: wentylacja
    # Optional background (overwrites the global background).
    background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - sensor.wentylatory_reku_went_out
          - sensor.wentylatory_reku_went_in
          - input_number.went_in
          - input_number.went_out
        state_filter:
          - 'home'
        card:
          type: glance
          title: Wentylacja_card

        # The picture entity card will represent an entity with a picture
      - type: picture-entity
        image: https://www.home-assistant.io/images/default-social.png
        entity: sensor.reku_wszystko
  - title: Wentylacja
    name: Example
    cards:
      - type: "custom:content-card-example"
        entity: input_boolean.switch_tv
    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # Title of the view. Will be used as the tooltip for tab icon
    title: Second view
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - sensor.wentylatory_reku_went_out
          - sensor.wentylatory_reku_went_in
          - input_number.went_in
          - input_number.went_out
          - entity: light.living_room
            # Override the name to use
            name: LR Lights

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
  - title: testWent
    background: radial-gradient(crimson, skyblue)
        # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                #icon: mdi:arrow-bottom-right-bold-outline
                show_header_toggle: true
                title: Czerpnia
                entities:
                  - sensor.wentylatory_reku_went_in
                  - sensor.reku_temperatura_czerpni
              - type: entities
                #icon: mdi:arrow-bottom-right-bold-outline
                show_header_toggle: true
                title: Wywiew
                entities:
                  #- sensor.wentylatory_reku_went_in
                  - sensor.reku_temperatura_wywiewu
          - type: horizontal-stack
            cards:
              - type: entities
                #icon: mdi:arrow-bottom-right-bold-outline
                show_header_toggle: true
                title: Wyrzutnia
                entities:
                  - sensor.wentylatory_reku_went_out
                  - sensor.reku_temperatura_wyrzutni
              - type: entities
                #icon: mdi:arrow-bottom-right-bold-outline
                show_header_toggle: true
                title: Nawiew
                entities:
                  #- sensor.wentylatory_reku_went_in
                  - sensor.reku_temperatura_nawiewu
          - type: horizontal-stack
            cards:
              - type: gauge
                title: Wentylator czerpnia
                unit_of_measurement: '%'
                entity: sensor.wentylatory_reku_went_in
                severity:
                  green: 0
                  yellow: 45
                  red: 85
              - type: gauge
                title: Wentylator wyrzutnia
                unit_of_measurement: '%'
                entity: sensor.wentylatory_reku_went_out
                severity:
                  green: 0
                  yellow: 45
                  red: 85
      
